### ISSUE TITLE
[Sourcegraph for GitHub] The loading data processing blocks the whole page.

### ISSUE THREAD

**Issue by zheeeng** [sourcegraph/issues#30] opened 2017-10-19 02:25 UTC
Visiting some big repo or encountering slow speed network(not sure), Sourcegraph for Github freezes the page for a while.

**Comment by beyang** [comment] 2018-01-26 00:20
@zheeeng Can you provide a link to a repository that we can use to reproduce?

**Comment by zheeeng** [comment] 2018-01-26 01:36
For I often visiting https://github.com/microsoft/typescript, the block let me have to disable repo file tree feature. If possible, hope a fixing as soon.

**Comment by beyang** [comment] 2018-01-26 07:59
@ijsnow The Chrome extension hangs scrolling on https://github.com/microsoft/typescript when I visit it and the file sidebar icon never appears. How we can speed this up (or maybe disable if the tree is too large)?

**Comment by ijsnow** [comment] 2018-01-27 20:23
@beyang @zheeeng Sorry I missed this notification! Looks like @KattMingMing has a fix in for this already and is going to push a new version with it soon

**Comment by beyang** [comment] 2018-01-29 20:03
@zheeeng We've pushed a fix for this (v1.5.91) and it is live now. I've verified that the page does not freeze on my machine, so I will close this issue. Please re-open if you're still experiencing it, and thank you for reporting this bug.

**Comment by zheeeng** [comment] 2018-02-05 08:04
@beyang Still have this issue.

**Comment by beyang** [comment] 2018-02-06 23:05
@ijsnow or @KattMingMing can you take a look?

**Comment by KattMingMing** [comment] 2018-02-07 16:19
@zheeeng - Sorry to hear that you were still seeing this issue in v1.5.91, we have released a new version (Latest is v1.6.1) that addresses the multiple performance issues that were interfering with GitHub page navigation. Hope you're able to take a look and are no longer seeing issues. Thank you again for your patience and bringing this issue to our attention. Cheers.

**Comment by zheeeng** [comment] 2018-02-08 10:11
The problem has gone. Upgraded to 1.6.2

**Comment by keegancsmith** [comment] 2018-02-08 11:10
🎉

**Closed by keegancsmith** 2018-02-08 11:10 UTC
Labels: bug
