### ISSUE TITLE
Go symbols slow to load on gousb

### ISSUE THREAD

**Issue by sqs** [sourcegraph/issues#58] opened 2018-04-12 23:52 UTC
User zagrodzki reported that symbols did not load at https://github.com/google/gousb/pull/34#issuecomment-378903512. (Let's not at-mention that person until it's fixed, to avoid wasting their time.)

**Comment by felixfbecker** [comment] 2018-04-13 01:56
Symbols work for me: https://sourcegraph.com/github.com/google/gousb

This is a trace for that repo of uncached symbol parsing: https://app.lightstep.com/sourcegraph-prod/trace?span_guid=746af54573237f8e&trace_id=53a4a9a897a00bd0&tracer_id=4c932b32bbcc3ef5&operation_name=parseUncached&at_micros=1523581513304071#span-746af54573237f8e

It's 100ms. Not sure what's going on

**Comment by slimsag** [comment] 2018-05-29 22:34
I don't know what the issue here was, but it is fixed or not happening anymore.

Symbols work very quickly in both the original repository AND in a new fork of the repo: https://sourcegraph.com/github.com/slimsag/gousb (they loaded in <1s, very quickly).

Closing since we cannot reproduce and I suspect other improvements to symbols have been made since.

**Closed by slimsag** 2018-05-29 22:34 UTC
