### ISSUE TITLE
Dark theme has light scrollbars / scrollbars where none are necessary

### ISSUE THREAD

**Issue by beyang** [sourcegraph/issues#38] opened 2018-01-31 02:16 UTC
- Issue type: bug report
- Sourcegraph version: sourcegraph.com
- OS Version: Linux, Chrome

Steps to reproduce:

1. Go to https://sourcegraph.com/github.com/Microsoft/TypeScript/-/blob/src/compiler/builderState.ts#L17:21
2. Set zoom to "90%" in Chrome (this is not necessary for all the scrollbars, but does cause a few more to show up.

![image](https://user-images.githubusercontent.com/1646931/35601784-b452c708-05e9-11e8-9792-8fd0dbc53fa5.png)

**Comment by sqs** [comment] 2018-01-31 02:36
The tooltip scrollbar should be fixed, but the others are not so simple.

We have looked into this issue in the past and did not find a good solution. It only happens on Linux (when Chrome overlay scrollbars aren't enabled, which I believe they are for google-chrome but not chromium dists) and macOS (when "show scrollbars when mouse is plugged in" is enabled in system preferences). Details below.

Recommended workaround: turn on overlay scrollbars in `chrome:flags` (Linux) or disable "show scrollbars when mouse is plugged in" (macOS)

-----

This is not as easy as it seems because when you style the scrollbars with CSS, they become non-overlay scrollbars. That means they take up more width when they are visible than when they are not. This causes page jitter as you navigate between pages, where one page needs a scrollbar and the other doesn't (or when the intermediate loading state doesn't need a scrollbar but both actual pages do).

I don't believe it's possible to have styled overlay scrollbars on Chrome. There are hits for that phrase on Google/SO, but none of them actually work and avoid the jitter issue.

**Comment by leosuccarferre** [comment] 2018-01-31 07:16
I looked into this a bit using a cross-browser emulator and it may be happening on other OS/browsers combos. I'll test some more.

**Comment by felixfbecker** [comment] 2018-01-31 07:35
Windows doesnt have overlay scrollbars at all.

But as I understand the issue title there are scrollbars when the content is not overflowing at all?

**Comment by beyang** [comment] 2018-01-31 18:14
We should just use `overflow: hidden` in the tooltips. The reason those show up is because the browser is zoomed out slightly, so even though they don't show up on the default 100% zoom, they do show up at 90% (because integer math). The default 100% zoom is too zoomed in for my liking, which is why I have it at 90%.

**Comment by felixfbecker** [comment] 2018-01-31 18:20
Imo cutting off tooltip content would look like a bug. vscode uses a scrollbar for tooltips. 

Even with 90% zoom the browser shouldn't render a scrollbar, I've never seen that before and have trouble reproducing

**Comment by beyang** [comment] 2018-01-31 18:20
It's off by like 1 pixel, so cutting it off shouldn't be an issue IMO

**Comment by felixfbecker** [comment] 2018-01-31 18:21
In your example it only shows "Loading", but what if it contains actual lines of code?

**Comment by sqs** [comment] 2018-03-30 08:38
I don't think we have any good options, and virtually all users' browsers have overlay scrollbars anyway.

**Closed by sqs** 2018-03-30 08:38 UTC
