### ISSUE TITLE
Redirect Loop with "httpToHttpsRedirect": "on"

### ISSUE THREAD

**Issue by mhupman** [sourcegraph/issues#98] opened 2018-06-21 15:40 UTC
- **Sourcegraph version:** 2.9.1
- **Platform:** Deployed according to https://about.sourcegraph.com/docs/deploy/aws

#### Steps to reproduce:

1. Set tlsCert, tlsKey, and appUrl to https:// (e.g. `https://sourcegraph.company.com`)
2. Restart server
3. Access via https://, works as expected
4. Set `httpToHttpsRedirect` to `on`
5. Restart server
6. Access via https://, enter infinite redirect loop

#### Actual: Entered infinite redirect loop

Note: The http -> https redirect was working in the prior version of SourceGraph before we updated to latest... I think it was 2.8.9.

**Comment by dadlerj** [comment] 2018-06-21 16:40
Thanks @mhupman, we're looking into this. For now, can you try setting this config option to "load-balanced" to see if it fixes the issue? 

https://about.sourcegraph.com/docs/config/site/#httptohttpsredirect

**Comment by mhupman** [comment] 2018-06-21 16:53
@dadlerj Same result with 'load-balanced' - infinite redirect.  Here are the headers of the first redirect from Chrome Dev Tools Network tab:

```
General

Request URL: https://sourcegraph.company.com/site-admin/configuration
Request Method: GET
Status Code: 301 
Remote Address: 10.200.5.60:443
Referrer Policy: no-referrer-when-downgrade


Response Headers

content-length: 92
content-type: text/html; charset=utf-8
date: Thu, 21 Jun 2018 16:49:33 GMT
location: https://sourcegraph.company.com/site-admin/configuration
status: 301

Request Headers

:authority: sourcegraph.company.com
:method: GET
:path: /site-admin/configuration
:scheme: https
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
accept-encoding: gzip, deflate, br
accept-language: en,en-US;q=0.9,pt;q=0.8,pt-BR;q=0.7,pt-PT;q=0.6,de;q=0.5,es;q=0.4
cache-control: max-age=0
cookie: [...snip...]
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
```

**Comment by beyang** [comment] 2018-06-21 21:13
The issue has been fixed in `master`, but reopening pending cutting the patch release.

**Comment by beyang** [comment] 2018-06-21 23:36
@mhupman Sourcegraph Server 2.9.2 has now been released and should fix this issue.

Since the Sourcegraph UI is likely inaccessible due to the redirect loop, could you try the following?

* ssh into your EC2 instance:
```
ssh -i ~/.ssh/${YOUR_KEY} ec2-user@${YOUR_INSTANCE_IP}
```
* Kill the existing Sourcegraph
```
docker kill $(docker ps | awk '{ print $1 }' | tail -n1)
```
* Pull the new image
```
docker pull sourcegraph/server:latest
```
* Start a new instance of Sourcegraph
```
docker run -d --publish 80:7080 --publish 443:7443 --restart unless-stopped --volume /home/ec2-user/.sourcegraph/config:/etc/sourcegraph --volume /home/ec2-user/.sourcegraph/data:/var/opt/sourcegraph sourcegraph/server:latest &
```
* Navigate to your instance address ("https://${YOUR_IP}" or whatever you've set `appURL` to, including the port if not 443).

We've confirmed this fix on an AWS instance we've spun up that matches the config parameters you described. However, if you run into additional issues, please let us know!

**Comment by mhupman** [comment] 2018-06-22 13:31
@beyang @dadlerj Worked like a charm - thanks!

**Comment by dadlerj** [comment] 2018-06-22 15:57
Great!

**Closed by dadlerj** 2018-06-22 15:57 UTC
Labels: bug, p1
