### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by janosimas** [sourcegraph/issues#115] opened 2018-08-02 13:31 UTC
- **Sourcegraph version:** "Sourcegraph.com"
- **Platform:** 
Ubuntu 16.04
Chrome 68.0.3440.75

#### Steps to reproduce:

1. Move the mouse over any variable or method

#### Expected: 
Not sure what to expect, I just installed the chrome extension to try.

#### Actual:
Pop up with the message:
    Dial tcp 138.197.51.210:9003: connect: connection refused

The message has some variations when I clink in 'Go to definition' or find references.

**Comment by felixfbecker** [comment] 2018-08-02 13:36
Hi @janosimas, do you have a link to the file you were looking at? I cannot reproduce this on my end in e.g. https://github.com/gorilla/mux/blob/master/mux.go

**Comment by janosimas** [comment] 2018-08-02 13:41
Hi @felixfbecker your file worked for me too.

Here is an example file that is not working for me:
https://github.com/TerraMA2/terrama2/blob/master/src/terrama2/services/appserver/main.cpp

**Comment by janosimas** [comment] 2018-08-02 13:51
@felixfbecker I think I kind of found the problem, it's a C++ code.
for what I see sourcegraph.com doesn't give c++ support, only the installed version.

But the error message could be improved! :-D

**Comment by chrismwendt** [comment] 2018-08-03 03:48
@janosimas Thanks for reporting this. Unfortunately, even after resolving the connection issue, C++ code intelligence is timing out on that repository. We have some ideas about how to improve the clone times, and I'll post back here with updates as they happen.

**Closed by chrismwendt** 2018-08-03 03:48 UTC
